### ISSUE TITLE
Error: Cannot find module 'j2c-importer'

### ISSUE THREAD

**Issue by futurist** [j2css/j2c-importer#1]
after `npm install j2c-importer --save`, with below app.js:

```
var importer = require('j2c-importer')
var obj = importer.toJ2c('a {background-color: red;}', {case:'camel'})
console.log(obj)
```

then `node app` below error thrown:

>  Error: Cannot find module 'j2c-importer'

delete and reinstall j2c-importer with no luck.

Tested the CLI version works very good, convert big CSS file with no error found, excellent!

**Comment by pygy** [comment]
Thanks, I had forgotten to add the `main` field in the `package.json` file...

I just pushed `v0.2.0`. Is it working now?
